spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
  docker:
    compose:
      file: ./docker/compose.yaml

  flyway:
    locations: filesystem:src/main/resources/db/migration
