# metaData
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
# specifcation
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
# Status (auto gen)

