openapi: '3.0.1'

info:
  title: User
  version: 1
  description: user resources

servers:
  - url: http://localhost/api
    description: Local server
tags:
  - name: User
    description: User

paths:
  '/user':
    post:
      tags:
        - User
      summary:
      operationId: saveUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/component/schemas/UserDTO'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/component/schemas/UserDTO'




components:
  schemas:
    UserDTO:
      type: object
      description: Data element for user
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        phoneNumber:
          type: string


